# Generated by Django 6.0.5 on 2026-06-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_course_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TechMantra', max_length=100)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site_logos/')),
                ('contact_email', models.CharField(default='info@techmantra.com', max_length=100)),
                ('contact_phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('contact_address', models.TextField(default='Academy Address, Delhi, India')),
            ],
        ),
    ]
