# Generated by Django 6.0.5 on 2026-06-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_adminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=150)),
                ('course_name', models.CharField(max_length=150)),
                ('rank', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('duration', models.CharField(max_length=50)),
                ('issue_date', models.CharField(max_length=100)),
                ('grade', models.CharField(default='N/A', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='contact_email',
            field=models.CharField(default='info@teachmantra.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='site_name',
            field=models.CharField(default='TeachMANTRA', max_length=100),
        ),
    ]
