# Generated by Django 5.2.16 on 2026-08-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_broadcastemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='popup_btn1_link',
            field=models.CharField(default='/admissions/', max_length=150),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='popup_btn1_text',
            field=models.CharField(default='Register Now', max_length=50),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='popup_btn2_link',
            field=models.CharField(default='/courses/', max_length=150),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='popup_btn2_text',
            field=models.CharField(default='Explore Courses', max_length=50),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='popup_image',
            field=models.ImageField(blank=True, null=True, upload_to='popup_banners/'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='popup_phone',
            field=models.CharField(default='+91 98765 43210, +91 91234 56789', max_length=100),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='popup_subtitle',
            field=models.TextField(default='Join the league of successful students at TeachMANTRA Academy. Job-oriented classroom coaching, structured mock tests & expert guidance. Register today to secure your seat!'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='popup_title',
            field=models.CharField(default='ADMISSION OPEN 2026-27', max_length=150),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='show_popup',
            field=models.BooleanField(default=True, help_text='Show automatic announcement popup on website load'),
        ),
    ]
