# Generated by Django 5.2.16 on 2026-09-04 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_websitesettings_popup_btn1_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='GS MIX — Online Quiz', max_length=200)),
                ('category', models.CharField(default='Mixed General Studies', max_length=100)),
                ('subtitle', models.CharField(default='परीक्षा अभ्यास • Comprehensive Mock Test Series', max_length=250)),
                ('description', models.TextField(blank=True, default='Practice general knowledge, current affairs, and mock test questions designed by TeachMANTRA expert faculty.')),
                ('duration_minutes', models.IntegerField(default=30, help_text='Test time in minutes')),
                ('total_questions', models.IntegerField(default=50, help_text='Target question count')),
                ('pass_percentage', models.IntegerField(default=40, help_text='Passing percentage (e.g. 40)')),
                ('external_link', models.CharField(blank=True, help_text='Optional external test portal or Google Form URL. Leave blank for interactive built-in portal.', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show in Home Page and Tests portal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='popup_btn1_link',
            field=models.CharField(default='/register/', max_length=150),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Question statement (Supports Hindi and English)')),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], default='A', max_length=5)),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown after test completion', null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='myapp.onlinetest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('score', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('passed', models.BooleanField(default=False)),
                ('answers_json', models.TextField(blank=True, help_text='Recorded answers for review', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='myapp.onlinetest')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
