# Generated by Django 5.2.16 on 2026-09-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_testsubmission_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='e.g. CO-FOUNDER, TEAM LEAD (FULL STACK)', max_length=150)),
                ('member_type', models.CharField(choices=[('founder', 'Co-Founder / Visionary'), ('team', 'Team Member / Faculty')], default='team', max_length=20)),
                ('tag_color', models.CharField(default='orange', help_text='orange or blue', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_images/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers come first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
