# Generated by Django 5.2.16 on 2026-09-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopperResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('exam_name', models.CharField(help_text='e.g. UP POLICE 2024, RRB NTPC 2024, NDA 2024', max_length=150)),
                ('rank', models.CharField(help_text='e.g. AIR 16753, AIR 29, 98.6%', max_length=100)),
                ('badge', models.CharField(default='Rank 1', help_text='e.g. Rank 1, Topper, Selected', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='toppers/')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
