# Generated by Django 5.2.16 on 2026-09-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_topperresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topperresult',
            name='badge',
            field=models.CharField(blank=True, default='', help_text='e.g. Rank 1, Topper (Optional - leave blank if not assigned)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='topperresult',
            name='rank',
            field=models.CharField(blank=True, default='', help_text='e.g. AIR 16753, AIR 29 (Optional - leave blank if not assigned)', max_length=100, null=True),
        ),
    ]
