# Generated by Django 5.2.16 on 2026-09-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_topperresult_badge_alter_topperresult_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubmission',
            name='unanswered_count',
            field=models.IntegerField(default=0, help_text='Unanswered count'),
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='wrong_count',
            field=models.IntegerField(default=0, help_text='Incorrect answers count'),
        ),
        migrations.AlterField(
            model_name='testsubmission',
            name='score',
            field=models.IntegerField(default=0, help_text='Correct answers count'),
        ),
    ]
