# Generated by Django 5.2.16 on 2026-09-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_testsubmission_unanswered_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='contact_email',
            field=models.CharField(default='info@theteachmantra.com', max_length=100),
        ),
    ]
