# Generated by Django 5.2.16 on 2026-09-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_websitesettings_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='contact_email',
            field=models.CharField(default='theteachmantra@gmail.com', max_length=100),
        ),
    ]
