# Generated by Django 5.2.16 on 2026-09-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_websitesettings_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='brochure_pdf',
            field=models.FileField(blank=True, help_text='Training & Courses Brochure PDF', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='syllabus_pdf',
            field=models.FileField(blank=True, help_text='Official Academy Syllabus PDF for students to download', null=True, upload_to='documents/'),
        ),
    ]
