# Generated by Django 5.2.16 on 2026-09-12 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_websitesettings_brochure_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. SSC GD Complete Math & Reasoning Syllabus 2026', max_length=250)),
                ('course', models.CharField(default='All Courses', help_text='e.g. SSC GD, UP Police, Railway, Computer, All Courses', max_length=150)),
                ('category', models.CharField(choices=[('Syllabus', 'Official Syllabus (पाठ्यक्रम)'), ('Daily Notes', 'Daily Class Notes (दैनिक नोट्स)'), ('Practice Sheet', 'Practice Sheet / DPP (अभ्यास पत्र)'), ('Previous Papers', 'Previous Year Papers (पुराने प्रश्नपत्र)'), ('Current Affairs', 'Current Affairs (समसामयिकी)'), ('Other', 'Other Study Material (अन्य सामग्री)')], default='Syllabus', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Brief details or chapter outline', null=True)),
                ('pdf_file', models.FileField(upload_to='syllabus_documents/')),
                ('document_date', models.DateField(default=django.utils.timezone.now, help_text='Date of syllabus or daily note release')),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-document_date', '-uploaded_at'],
            },
        ),
    ]
