# Generated by Django 5.2.16 on 2026-09-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_syllabusdocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('competitive', 'Competitive Exam & Certificate Courses'), ('monthly', 'Monthly Plans'), ('package', 'Special Monthly Packages'), ('other', 'Other Courses')], default='competitive', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
